import FlowbarLayout from '../components/FlowbarLayout';
import './global.css';

export const metadata = {
  title: 'Fordring Blog',
  description: 'Generated by Leslie',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-deep-background overflow-x-hidden">
        <FlowbarLayout>{children}</FlowbarLayout>
      </body>
    </html>
  );
}
